### PR TITLE
1  HoughP image line detection

### LINKED ISSUE #1: [TASK]  Pool Wall Detection - Sonar Image Line Detection
### Description of task

This task is about using the sonar data and decompose and try to find out where the walls are.
The scope of this task is just to detect the lines on the 2d sonar image. 
Lines are parametrized by rho and theta.

- rho is the shortest(perpendicular) distance from origo to the lines.
- theta is the corresponding angle between the perpendicular line and origin.

Follow the convention of having the top-left corner of the image be the origin, and with a clockwise direction for positive angle. 

### Suggested Workflow

1. Familiarize yourself with the sonar data
2. Find out if you have to convert between Cartesian and polar coordinates to make the walls straight.
3. Find out what line detection algorithm to use. There are many options including:  Hough transform using OpenCV, Ransac on pixel coordinates or other alternatives (@gardeg).
4. Make the detected lines(measurements) ready for injection into the [line filtering library](https://github.com/vortexntnu/vortex-auv/issues/650)

### Specifications

- Should use [SonarInfo](https://github.com/vortexntnu/vortex-msgs/blob/main/msg/SonarInfo.msg) message to extract endpoint of lines if available to enforce a min-length of detected lines.
- Look into the possibility of 

### Contacts

@jorgenfj 
@fnilsen1 For SonarInfo definition
@rom-thom (Thomas Paulen) to discuss pre-processing of the sonar images

### Code Quality

- [ ] Every function in header files are documented (inputs/returns/exceptions)
- [ ] The project has automated tests that cover MOST of the functions and branches in functions (pytest/gtest)
- [ ] The code is documented on the wiki (provide link)

### PR DESCRIPTION
**Pull request by jorgenfj**

### CODE REVIEW

File: line_detection_houghp/include/line_detection_houghp/lib/utils.hpp
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/lib/utils.hpp:1]: Why are all of these functions inlined in the header file, and why is there two header files that could be one? I would rather declare all the functions in one header file (drop `inline`) and implement them in a `.cpp` file

File: line_detection_houghp/include/line_detection_houghp/lib/utils.hpp [hunk 1]
```diff
@@ -0,0 +1,146 @@
...
+const cv::Scalar kLineColor(0, 0, 255);  // BGR red
+
+inline void make_overlay_color(const cv::Mat& input_bgr,
+                               const cv::Mat& gray8,
+                               const std::vector<cv::Vec4i>& lines,
+                               cv::Mat& out_bgr) {
+    if (input_bgr.empty()) {
+        throw std::runtime_error("make_overlay_color: input_bgr is empty");
+    }
+    out_bgr = vortex::line_detection::to_bgr8(input_bgr, gray8);
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/lib/utils.hpp]: Seems like `out_bgr` is unconditionally overwritten here, so returning `out_bgr` by value would be clearer imo. And probably wont affect performance

File: line_detection_houghp/include/line_detection_houghp/lib/utils.hpp [hunk 2]
```diff
@@ -0,0 +1,146 @@
...
+        cv::normalize(input, out, 0, 255, cv::NORM_MINMAX, CV_8U);
+        return out;
+    }
+
+    throw std::runtime_error("to_bgr8_for_overlay: unsupported channel count");
+}
+
+constexpr int kLineThickness = 2;
+constexpr int kLineType = cv::LINE_AA;
+const cv::Scalar kLineColor(0, 0, 255);  // BGR red
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/lib/utils.hpp]: Mix of naming style?

File: line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp [hunk 3]
```diff
@@ -0,0 +1,91 @@
...
+#include <vortex_msgs/msg/line_segment2_d_array.hpp>
+#include "line_detection_houghp/lib/line_detection_houghp.hpp"
+
+namespace vortex::line_detection {
+
+class LineDetectionHoughPNode : public rclcpp::Node {
+   public:
+    explicit LineDetectionHoughPNode(const rclcpp::NodeOptions& options);
+
+    ~LineDetectionHoughPNode() {}
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp]: Default it?

File: line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp [hunk 4]
```diff
@@ -0,0 +1,91 @@
...
+#include <memory>
+#include <rclcpp/node.hpp>
+#include <rclcpp/node_options.hpp>
+#include <rclcpp/parameter_event_handler.hpp>
+#include <rclcpp/publisher.hpp>
+#include <rclcpp/rclcpp.hpp>
+#include <sensor_msgs/msg/image.hpp>
+#include <std_msgs/msg/header.hpp>
+#include <vortex_msgs/msg/detail/line_segment2_d_array__struct.hpp>
+#include <vortex_msgs/msg/line_segment2_d_array.hpp>
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp]: Why is the detail header included? Doesnt the "normal" one cover what you need?

File: line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp [hunk 5]
```diff
@@ -0,0 +1,91 @@
+#ifndef LINE_DETECTION_HOUGHP__ROS__LINE_DETECTION_HOUGHP_ROS_HPP_
+#define LINE_DETECTION_HOUGHP__ROS__LINE_DETECTION_HOUGHP_ROS_HPP_
+
+#include <cv_bridge/cv_bridge.h>
+#include <memory>
+#include <rclcpp/node.hpp>
+#include <rclcpp/node_options.hpp>
+#include <rclcpp/parameter_event_handler.hpp>
+#include <rclcpp/publisher.hpp>
+#include <rclcpp/rclcpp.hpp>
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp]: Just whinging it, but I dont see cv bridge being used in this file, so it should probably be included where it is used instead. And you already include node, node options, param event handler and publisher, so probably no need for rclcpp include then?

File: line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp [hunk 6]
```diff
@@ -0,0 +1,91 @@
...
+
+   private:
+    rclcpp::Subscription<sensor_msgs::msg::Image>::SharedPtr image_sub_;
+    rclcpp::Publisher<vortex_msgs::msg::LineSegment2DArray>::SharedPtr
+        line_segments_pub_;
+    rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr color_overlay_pub_;
+    rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr canny_debug_pub_;
+    rclcpp::Publisher<sensor_msgs::msg::Image>::SharedPtr canny_overlay_pub_;
+
+    void image_callback(const sensor_msgs::msg::Image::SharedPtr msg);
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/ros/line_detection_houghp_ros.hpp]:
```C++
const sensor_msgs::msg::Image::SharedPtr& msg
```
instead?

File: line_detection_houghp/include/line_detection_houghp/lib/line_detection_houghp.hpp [hunk 7]
```diff
@@ -0,0 +1,36 @@
+#ifndef LINE_DETECTION_HOUGHP__LIB__HOUGHP_LINE_DETECTION_HPP_
+#define LINE_DETECTION_HOUGHP__LIB__HOUGHP_LINE_DETECTION_HPP_
+
+#include <opencv2/core.hpp>
+#include <opencv2/imgproc.hpp>
+#include <vector>
+#include <vortex/utils/types.hpp>
+#include <lib/filters/all_filters.hpp>
+#include "typedefs.hpp"
```
Comment (Andeshog) [inline line_detection_houghp/include/line_detection_houghp/lib/line_detection_houghp.hpp]: am I blind or doesnt this file exist?

```C++
#include <lib/filters/all_filters.hpp>
```

File: line_detection_houghp/launch/line_detection_houghp.launch.py [hunk 8]
```diff
@@ -0,0 +1,28 @@
...
+        [
+            Node(
+                package='line_detection_houghp',
+                executable='line_detection_houghp_node',
+                name='line_detection_houghp',
+                output='screen',
+                parameters=[
+                    config,
+                    # {'use_sim_time': True} # If testing with rosbags sim_time might be preferred if bag is looped
+                ],
```
Comment (Andeshog) [inline line_detection_houghp/launch/line_detection_houghp.launch.py]: then I would have it, but default it to false

File: line_detection_houghp/src/ros/line_detection_houghp_ros_utils.cpp [hunk 9]
```diff
@@ -0,0 +1,139 @@
...
+    return s.size() >= prefix.size() &&
+           s.compare(0, prefix.size(), prefix) == 0;
+}
+
+static DetectorMode parse_mode(const std::string& s) {
+    if (s == "standard")
+        return DetectorMode::standard;
+    if (s == "visualize")
+        return DetectorMode::visualize;
+    if (s == "debug")
```
Comment (Andeshog) [inline line_detection_houghp/src/ros/line_detection_houghp_ros_utils.cpp]: When comparing against these "raw" strings, i feel it would be cleaner and less bug prone to make them constexpr (and put them in the header file, but it doesnt seem to be a header file with this one?)

File: line_detection_houghp/src/ros/line_detection_houghp_ros.cpp [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+        this->get_parameter("topic.canny_debug_pub_topic").as_string();
+    const std::string canny_overlay_pub_topic =
+        this->get_parameter("topic.canny_overlay_pub_topic").as_string();
+
+    auto qos_profile = vortex::utils::qos_profiles::sensor_data_profile(1);
+
+    image_sub_ = this->create_subscription<sensor_msgs::msg::Image>(
+        image_sub_topic, qos_profile,
+        std::bind(&LineDetectionHoughPNode::image_callback, this,
+                  std::placeholders::_1));
```
Comment (Andeshog) [inline line_detection_houghp/src/ros/line_detection_houghp_ros.cpp]: lambda perhaps 😁

File: line_detection_houghp/src/ros/line_detection_houghp_ros.cpp [hunk 11]
```diff
@@ -0,0 +1,136 @@
...
+    const std::string line_segments_pub_topic =
+        this->get_parameter("topic.line_segments_pub_topic").as_string();
+    const std::string color_overlay_pub_topic =
+        this->get_parameter("topic.color_overlay_pub_topic").as_string();
+    const std::string canny_debug_pub_topic =
+        this->get_parameter("topic.canny_debug_pub_topic").as_string();
+    const std::string canny_overlay_pub_topic =
+        this->get_parameter("topic.canny_overlay_pub_topic").as_string();
+
+    auto qos_profile = vortex::utils::qos_profiles::sensor_data_profile(1);
```
Comment (Andeshog) [inline line_detection_houghp/src/ros/line_detection_houghp_ros.cpp]: Is there a reason this cant be const?

File: line_detection_houghp/src/ros/line_detection_houghp_ros_utils.cpp [hunk 12]
```diff
@@ -0,0 +1,139 @@
...
+        {
+            cv_bridge::CvImage m;
+            m.header = header;
+            m.encoding = sensor_msgs::image_encodings::BGR8;
+            m.image = dbg->overlay_color;
+            color_overlay_pub_->publish(*m.toImageMsg());
+        }
+
+        return;
+    }
```
Comment (Andeshog) [inline line_detection_houghp/src/ros/line_detection_houghp_ros_utils.cpp]: switch or elifs here instead?

File: dependencies.repos [hunk 13]
```diff
@@ -0,0 +1,7 @@
+repositories:
```
Comment (Andeshog) [inline dependencies.repos:1]: Doesnt it also depend on the image repo?

File: line_detection_houghp/include/line_detection_houghp/lib/line_detection_houghp.hpp (hunk 7 above)
Comment (jorgenfj) [reply line_detection_houghp/include/line_detection_houghp/lib/line_detection_houghp.hpp]: I am the blind one🤡
